name: Angular CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: '14.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build --prod

    - name: Deploy to production
      run: |
        # Deployment script here
        echo "Deployment successful!"
